basePath: /v0
consumes:
    - application/json
definitions:
    IdentifiablePerson:
        properties:
            id:
                type: string
            avatarUrlStr:
                type: string
                x-nullable: true
            prename:
                type: string
            surname:
                type: string
        required:
            - id
            - prename
            - surname
        type: object
    Retailer:
        properties:
            logoUrlStr:
                type: string
                x-nullable: true
            name:
                type: string
        required:
            - name
        type: object
info:
    title: TSOA
    version: 1.0.0
    description: 'Build swagger-compliant REST APIs using TypeScript and Node'
    license:
        name: MIT
paths:
    /persons:
        get:
            operationId: GetPersonsSync
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/IdentifiablePerson'
            security: []
            parameters: []
    '/persons/{id}':
        get:
            operationId: GetPersonSync
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        $ref: '#/definitions/IdentifiablePerson'
            security: []
            parameters:
                -
                    in: path
                    name: id
                    required: true
                    type: string
    /retailers:
        post:
            operationId: Create
            produces:
                - application/json
            responses:
                '201':
                    description: Created
                '400':
                    description: 'Bad Request'
            security: []
            parameters:
                -
                    in: body
                    name: requestBody
                    required: true
                    schema:
                        $ref: '#/definitions/Retailer'
produces:
    - application/json
swagger: '2.0'
securityDefinitions: {}
host: 'localhost:8080'
