language: node_js

services:
  - docker

before_install:
  - docker build -t xelement/money-server .

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - gulp test
  - docker push xelement/money-server
