language: minimal

services:
  - docker

before_install:
  - ls -a # FIXME: Remove this once "debugging" is done
  - docker build -t xelement/money-server .

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - gulp test
  - docker push xelement/money-server
