language: minimal

services:
  - docker

before_install:
  - docker build -t xelement/money-server .
  - docker run -d xelement/money-server /bin/sh

script:
  - npm list -g --depth=0
  - ls
  - gulp test

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push xelement/money-server
  on:
    branch: master
