language: minimal

services:
  - docker

jobs:
  includes:
    - stage: "Docker build"
      script: docker build -t xelement/money-server .
    - stage: "Test (in Docker)"
      script: docker run -t xelement/money-server /bin/sh -c "gulp test"
    - stage: "Deploy (in Docker)"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push xelement/money-server
