language: minimal

services:
  - docker

jobs:
  include:
    - script: docker build -t money-server .
    - script: docker run -t money-server /bin/sh -c "gulp test"
    - stage: deploy
      name: "Deploy to Docker Hub"
      script:
        - docker tag money-server xelement/money-server
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push xelement/money-server
