language: minimal

services:
  - docker

before_install:
  - docker build -t xelement/money-server .

script:
  - gulp test

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push xelement/money-server
  on:
    branch: master
