language: minimal

services:
  - docker

before_install:
  - docker build -t xelement/money-server .

script:
  - docker run -t xelement/money-server /bin/sh -c "gulp test"

deploy:
  skip_cleanup: true
  provider: script
  script: ./etc/travis/docker_push.sh
  on:
    branch: master
