trigger:
  branches:
   include:
     - '*'

resources:
- repo: self

variables:
  tag: $(Build.BuildId)

stages:
- stage: build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: deploy
  displayName: Deploy to Docker Hub
  dependsOn: build
  jobs:
  - job: deploy
    displayName: Deploy to Docker Hub
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub (via xelementbot)'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub (via xelementbot)'
        repository: 'money-server'
        command: 'push'
