trigger:
  branches:
   include:
     - '*'


resources:
- repo: self


variables:
  docker_connection: 'Docker Hub (via xelementbot)' # see https://xelement.visualstudio.com/money-server/_settings/adminservices
  docker_image_name: xelement/money-server
  docker_tag: latest


stages:

- stage: build
  displayName: Build
  jobs:
  - job: build-docker
    displayName: Build Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build default Docker image
      inputs:
        command: build
        dockerfile: './Dockerfile'
        repository: $(docker_image_name)
        tags: |
          $(docker_tag)

- stage: deploy
  displayName: Deploy
  dependsOn: build
  jobs:
  - job: deploy-dockerhub-latest
    displayName: Deploy to Docker Hub as latest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      command: login
      containerRegistry: $(docker_connection)
    - task: Docker@2
      command: push
      containerRegistiry: $(docker_connection)
      repository: $(docker_image_name)
      tags: |
        $(docker_tag)
