trigger:
  branches:
   include:
     - '*'


resources:
- repo: self


variables:
  docker_connection: 'Docker Hub (via xelementbot)' # see https://xelement.visualstudio.com/money-server/_settings/adminservices


steps:

  - task: DockerInstaller@0
    displayName: Install Docker

  - bash: docker build -t money-server .

  - bash: docker run -t money-server /bin/sh -c "gulp test"

  - bash: docker tag money-server xelement/money-server:latest
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: $(docker_connection)
  - bash: docker push xelement/money-server:latest
