trigger:
  branches:
   include:
     - '*'


resources:
- repo: self


variables:
  docker_connection: 'Docker Hub (via xelementbot)' # see https://xelement.visualstudio.com/money-server/_settings/adminservices
  is_master: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  local_docker_image: 'money-server:latest'
  remote_docker_image: 'xelement/money-server:latest'


steps:

  - task: DockerInstaller@0
    displayName: Install Docker

  - bash: docker build -t $(local_docker_image) .
    displayName: Build

  - bash: docker run -t $(local_docker_image) /bin/sh -c "gulp test"
    displayName: Test

  - bash: docker tag $(local_docker_image) $(remote_docker_image)
    condition: $(is_master)
    displayName: 'Deploy (1/3)'
  - task: Docker@2
    displayName: 'Deploy (2/3)'
    condition: $(is_master)
    inputs:
      command: 'login'
      containerRegistry: $(docker_connection)
  - bash: docker push $(remote_docker_image)
    displayName: 'Deploy (3/3)'
    condition: $(is_master)
