trigger:
  branches:
   include:
     - '*'

resources:
- repo: self

variables:
  docker_connection: 'Docker Hub (via xelementbot)' # see https://xelement.visualstudio.com/money-server/_settings/adminservices

steps:
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: $(docker_connection)
  - task: Docker@2
    displayName: Build and push Docker Image
    inputs:
      command: buildAndPush
      containerRegistry: $(docker_connection)
      dockerfile: './Dockerfile'
      repository: 'xelement/money-server'
      tags: |
        latest
