trigger:
  branches:
   include:
     - '*'


resources:
- repo: self


variables:
  docker_connection: 'Docker Hub (via xelementbot)' # see https://xelement.visualstudio.com/money-server/_settings/adminservices
  local_docker_image: 'money-server:latest'
  remote_docker_image: 'xelement/money-server:latest'


steps:

  - task: DockerInstaller@0
    displayName: Install Docker

  - bash: docker build -t $(local_docker_image) .

  - bash: docker run -t $(local_docker_image) /bin/sh -c "gulp test"

  - bash: docker tag $(local_docker_image) $(remote_docker_image)
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: $(docker_connection)
  - bash: docker push $(remote_docker_image)
