trigger:
  branches:
   include:
     - '*'


resources:
- repo: self


variables:
  docker_connection: 'Docker Hub (via xelementbot)' # see https://xelement.visualstudio.com/money-server/_settings/adminservices


jobs:

- job: install
  displayName: Install
  steps:
    - task: DockerInstaller@0
      displayName: Install Docker

- job: build
  displayName: Build
  dependsOn: install
  steps:
    - bash: docker build -t money-server .

- job: test
  displayName: Test
  dependsOn: build
  steps:
    - bash: docker run -t money-server /bin/sh -c "gulp test"

- job: deploy
  displayName: Deploy to Docker Hub
  dependsOn: test
  steps:
    - bash: docker tag money-server xelement/money-server:latest
    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: $(docker_connection)
    - bash: docker push xelement/money-server:latest
